#!/usr/bin/env python3
"""Regenerates data/mapdata.js from the verbatim JSON copies in data/ (MAPS_SLICE §5: copy maps_slice.json as is; a one-line
JS twin lets the game run from file:// without fetch). Run from the repo root after copying the JSON from design/specs."""
import json, pathlib
root = pathlib.Path(__file__).resolve().parent.parent / 'data'
d = {k: json.loads((root / f'{k}.json').read_text()) for k in ('maps_slice', 'interiors')}
(root / 'mapdata.js').write_text('// GENERATED by tools/gen_mapdata.py from data/maps_slice.json + data/interiors.json (verbatim copies of design/specs). Do not edit.\n'
                                 'const MAPDATA = ' + json.dumps(d, separators=(',', ':'), ensure_ascii=False) + ';\n')
print('wrote', root / 'mapdata.js')
