#!/usr/bin/env python3
"""Regenerates data/mapdata.js from the verbatim JSON copies in data/ (MAPS_SLICE §5: copy each JSON as is; a one-line
JS twin lets the game run from file:// without fetch). Run from the repo root after copying the JSON from design/specs.
Merge order in the game: maps_slice, interiors, act1_route2, cobblecrest."""
import json, pathlib
root = pathlib.Path(__file__).resolve().parent.parent / 'data'
names = ('maps_slice', 'interiors', 'act1_route2', 'cobblecrest')
d = {k: json.loads((root / f'{k}.json').read_text()) for k in names}
(root / 'mapdata.js').write_text('// GENERATED by tools/gen_mapdata.py from data/' + ' + '.join(n + '.json' for n in names) + ' (verbatim copies of design/specs). Do not edit.\n'
                                 'const MAPDATA = ' + json.dumps(d, separators=(',', ':'), ensure_ascii=False) + ';\n')
print('wrote', root / 'mapdata.js')
